### ISSUE TITLE
link-mechanics #1

### ISSUE THREAD

**Issue by kairav** [SoftwareEngineeringToolDemos/ICSE-2011-UMLsec#1]
The link which is mentioned as containing the user manual, redirects to the home page of a professor.

**Comment by RimiChen** [comment]
Hi~
I see the link works properly. Did you fix it? or just some misunderstanding?

If you fixed them, may you need to use pull requests (according to assignment instructions).

**Comment by kairav** [comment]
" For more information which functions and examples are already working with this version visit the user-manual-pages at: http://ls14-www.cs.tu-dortmund.de/main2/jj/umlsectool/users_new.html"

But the link which is provided opens up the page of a professor. Not clear about where to find the user manual pages.

**Comment by RimiChen** [comment]
Hi~

Thank you for giving more details.
I know where the problem was. But, I am not sure that I can fix the question.

The message that "" For more information which functions and examples are already working with this version visit the user-manual-pages at: http://ls14-www.cs.tu-dortmund.de/main2/jj/umlsectool/users_new.html""

are copied from author's original README.txt

Since the assignment instruction said that if the tools have README file already, we should append ours to the original one.

I am not sure that if there are something wrong in original file, can we correct they directly or not.

(But I still corrected it, anyway).
